### ISSUE TITLE
High level design

### ISSUE THREAD

**Issue by uyguronur** [AyranIsTheNewRaki/Herodot#19]
We have to create a high level design to have a handshake about the implementation.

**Comment by NurErtem** [comment]
i thought about it it might make sense to remove tangiable, intagiable etc. and minimize the UI interaction in terms of better UX. Also as client suggested we have to provide a certain set of options for the categories, so a drop down menu seems to be the best option. According to the client feedback, it also makes sense to reduce the CHO property to maybe 5 with limited set of drop down option for each property. 
i will create a visual and share with the team

**Comment by cantux** [comment]
I would vote on not making the fields dynamic but just support sets of predetermined properties

**Comment by idilgun** [comment]
I would too, my comment based on client feedback would be to increase the number of fields we have and make most of them optional instead of using dropdown - I think dropdown doesn't minimize user interaction or yield better UX

I think a good thing to do, as client suggested, would b to come up with a list of challenging CHOs and make our design as flexible as needed to insert these items.

**Comment by NurErtem** [comment]
ok instead of drop down what do you have in mind for choosing among the fields attached to a specific property? like for example for property:title, we can have museum, tradition, archaeological site etc listed. but what UI schema do we use? i guess it would be better to talk over an example. i will try to come up with one during the weekend.

**Comment by NurErtem** [comment]
@AyranIsTheNewRaki/ayranisthenewraki please have one more look at the design. @idilgun could you please implement the changes we have agreed on?

**Comment by idilgun** [comment]
sure, I will come up with a interface for the new introduced timeline idea in time for our meeting on Thursday so that we have something solid to talk over.

**Comment by NurErtem** [comment]
As i understand we will work on updating the pg2 of the mock up. Iwill also
try to come up with a version. We will see which one suits with
requirements. I have kindly asked you too since i was not very clear and
confused

**Comment by NurErtem** [comment]
the mockup v3 is on a shared google drive of heredot, editable by all team members. the latest versioin of the mock up was signed off. 
https://www.draw.io/?state=%7B%22ids%22:%5B%220B-1y2ZQCjTGvSG5Bd2RSd1hxajA%22%5D,%22action%22:%22open%22,%22userId%22:%22116507299009537651019%22%7D#G0B-1y2ZQCjTGvSG5Bd2RSd1hxajA
draw.io has also github integration so the v3 of the mock up will be published to github using drawio integration
